name: Build Controls

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bundle Component with Vite
        uses: actions/setup-node@v3
        with:
          node-version: "23"
          cache: "npm"
      - run: |
          npm ci
          npm run build --if-present
          mv dist omnis-dashboard
          tar -zcvf omnis-dashboard.tar.gz omnis-dashboard/
      - name: Upload Omnis Studio HTML Control artifact
        uses: actions/upload-artifact@v4
        with:
          name: omnis-dashboard
          path: omnis-dashboard.tar.gz
      - name: Extract package.json version
        if: startsWith(github.ref, 'refs/tags/')
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Build release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.package-version.outputs.current-version }}
          files: |
            omnis-dashboard.tar.gz
            LICENSE
