name: Build Histoire Pages

on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Bundle Component with Vite
        uses: actions/setup-node@v3
        with:
          node-version: "23"
          cache: "npm"
      - run: |
          npm ci
          HISTOIRE_PATH_PREFIX=/omnis-dashboard/ npm run story:build-ci --if-present
          mv .histoire/dist public
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    runs-on: ubuntu-latest

    # Add a dependency to the build job
    needs: build-pages

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      if: startsWith(github.ref, 'refs/tags/')
      id: deployment
      uses: actions/deploy-pages@v4