name: Build Histoire Pages

on: [push]

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bundle Component with Vite
        uses: actions/setup-node@v3
        with:
          node-version: "23"
          cache: "npm"
      - run: |
          npm ci
          npm run story:build-ci --if-present
          mv .histoire/dist public
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    runs-on: ubuntu-latest

    # Add a dependency to the build job
    needs: build-pages

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      if: startsWith(github.ref, 'refs/tags/')
      id: deployment
      uses: actions/deploy-pages@v4]